name: app_database_test
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  http: ^0.13.5
  sqflite: ^2.0.0+4
  path_provider: ^2.0.11
  path: ^1.8.3
  drift: ^2.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  isar:
    version: 3.1.8
    hosted: https://pub.isar-community.dev/
  isar_flutter_libs: # contains Isar Core
    version: 3.1.8
    hosted: https://pub.isar-community.dev/

dev_dependencies:
  flutter_test:
    sdk: flutter

  drift_dev: ^2.4.1
  build_runner: ^2.3.3
  isar_generator:
    version: 3.1.8
    hosted: https://pub.isar-community.dev/

flutter:
  uses-material-design: true
